-- This should be generated by the make system
module Data.Array.Parallel.Base.Config (
    debug
  , debugCritical
  , tracePrimEnabled
) where

debug                   = False
debugCritical           = False

-- | Print tracing information for each DPH primitive to console.
--   The tracing hooks are in dph-prim-par/D/A/P/Unlifted.hs
tracePrimEnabled        :: Bool
tracePrimEnabled        = False

