TOPDIR = ..
BINARIES = reglib

reglib_seq_FLAGS = -fsimplifier-phases=3
reglib_par_FLAGS = -fsimplifier-phases=3

reglib_DPH = reg
reglib_SOURCES =  ReglibTest.hs Array.hs 


include $(TOPDIR)/mk/test.mk
