TOPDIR = ..
BINARIES = raBench raTest saBench

raBench_seq_FLAGS = -fsimplifier-phases=3
raBench_par_FLAGS = -fsimplifier-phases=3

raBench_DPH = raBench
raBench_SOURCES =  ReglibBench.hs Array.hs ArrayExamples.hs DArray.hs DArrayExamples.hs Hierarchical.hs

raTest_seq_FLAGS = -fsimplifier-phases=3
raTest_par_FLAGS = -fsimplifier-phases=3

raTest_DPH = raTest
raTest_SOURCES =  ReglibTest.hs Array.hs ArrayExamples.hs DArray.hs DArrayExamples.hs Hierarchical.hs

saBench_seq_FLAGS = -fsimplifier-phases=3
saBench_par_FLAGS = -fsimplifier-phases=3

saBench_DPH = saBench
saBench_SOURCES =  ArrayBench.hs

include $(TOPDIR)/mk/test.mk
