TOPDIR = ..
BINARIES = matrixprim matrix

matrixprim_DPH = matrixprim
matrixprim_SOURCES =  MatrixPrimTest.hs MatrixPrim.hs

matrix_DPH = matrix
matrix_SOURCES =  MatrixTest.hs Matrix.hs


include $(TOPDIR)/mk/test.mk

