TOPDIR = ..
BINARIES = mksm smvm-c smvm prim

HCCFLAGS = -optc-O3

smvm_DPH = smvm
smvm_SOURCES = smvm.hs SMVMVect.hs

prim_DPH = prim
prim_SOURCES = prim.hs SMVMPrim.hs

include $(TESTDIR)/mk/test.mk
