TOPDIR = ..
BINARIES = quickhull QuickHull

HCCFLAGS = -optc-O3

quickhull_DPH = quickhull
quickhull_SOURCES = vect.hs QuickhullVect.hs Types.hs

QuickHull_SOURCES = QuickHull.hs
QuickHull_FLAGS   = -O2

include $(TOPDIR)/mk/test.mk
