TOPDIR = ..
BINARIES = delaunaySVG

HCCFLAGS = -optc-O3

delaunaySVG_DPH = delaunaySVG
delaunaySVG_SOURCES = svg.hs Types.hs Sort.hs Hull.hs Delaunay.hs
delaunaySVG_FLAGS = fno-liberate-case

include $(TOPDIR)/mk/test.mk
